// Generated by Phase 1 setup\n



/**
 * SINGLE PRISMA CLIENT INSTANCE
 * 
 * Centralized database connection management
 * Prevents connection pool exhaustion from multiple instances
 */

const { PrismaClient } = require('@prisma/client');

// Create single Prisma instance
const prisma = new PrismaClient({
  log: process.env.NODE_ENV === 'development' 
    ? ['query', 'info', 'warn', 'error']
    : ['error'],
});

// Graceful shutdown
process.on('beforeExit', async () => {
  await prisma.$disconnect();
});

module.exports = prisma;