// Generated by Phase 1 setup\n


/**
 * TRANSACTION MANAGER
 * 
 * Helper utilities for managing Prisma transactions
 */

const prisma = require('./prisma');

/**
 * Execute operations within a transaction
 * Automatically handles rollback on error
 * 
 * @param {Function} callback - Async function that receives transaction client
 * @returns {Promise<any>} Result of the transaction
 * 
 * @example
 * const result = await executeTransaction(async (tx) => {
 *   const user = await tx.user.create({ data: { ... } });
 *   const order = await tx.order.create({ data: { userId: user.id } });
 *   return { user, order };
 * });
 */
async function executeTransaction(callback) {
  return await prisma.$transaction(callback);
}

/**
 * Execute multiple operations in a transaction
 * 
 * @param {Array<Promise>} operations - Array of Prisma operations
 * @returns {Promise<Array>} Results of all operations
 * 
 * @example
 * const results = await executeTransactionBatch([
 *   prisma.user.create({ data: { ... } }),
 *   prisma.order.update({ where: { id: 1 }, data: { ... } })
 * ]);
 */
async function executeTransactionBatch(operations) {
  return await prisma.$transaction(operations);
}

module.exports = {
  executeTransaction,
  executeTransactionBatch,
};