// Generated by Phase 1 setup\n



/**
 * DATE UTILITIES
 * 
 * Helper functions for date manipulation and formatting
 */

const { TIMEZONE } = require('../../config/constants');

/**
 * Get current date in Lagos timezone
 */
function getCurrentDate() {
  return new Date();
}

/**
 * Add days to a date
 * 
 * @param {Date} date - Starting date
 * @param {number} days - Number of days to add
 * @returns {Date} New date
 */
function addDays(date, days) {
  const result = new Date(date);
  result.setDate(result.getDate() + days);
  return result;
}

/**
 * Subtract days from a date
 * 
 * @param {Date} date - Starting date
 * @param {number} days - Number of days to subtract
 * @returns {Date} New date
 */
function subtractDays(date, days) {
  return addDays(date, -days);
}

/**
 * Add hours to a date
 * 
 * @param {Date} date - Starting date
 * @param {number} hours - Number of hours to add
 * @returns {Date} New date
 */
function addHours(date, hours) {
  const result = new Date(date);
  result.setHours(result.getHours() + hours);
  return result;
}

/**
 * Check if a date is in the past
 * 
 * @param {Date} date - Date to check
 * @returns {boolean} True if date is in the past
 */
function isDateInPast(date) {
  return new Date(date) < new Date();
}

/**
 * Check if a date is within N days from now
 * 
 * @param {Date} date - Date to check
 * @param {number} days - Number of days
 * @returns {boolean} True if date is within N days
 */
function isWithinDays(date, days) {
  const targetDate = new Date(date);
  const futureDate = addDays(new Date(), days);
  return targetDate <= futureDate && targetDate >= new Date();
}

/**
 * Get start of day (00:00:00)
 * 
 * @param {Date|string} date - Date
 * @returns {Date} Start of day
 */
function getStartOfDay(date) {
  const d = new Date(date);
  d.setHours(0, 0, 0, 0);
  return d;
}

/**
 * Get end of day (23:59:59)
 * 
 * @param {Date|string} date - Date
 * @returns {Date} End of day
 */
function getEndOfDay(date) {
  const d = new Date(date);
  d.setHours(23, 59, 59, 999);
  return d;
}

module.exports = {
  getCurrentDate,
  addDays,
  subtractDays,
  addHours,
  isDateInPast,
  isWithinDays,
  getStartOfDay,
  getEndOfDay,
  TIMEZONE,
};