// Generated by Phase 1 setup\n



/**
 * PAGINATION UTILITIES
 * 
 * Reusable pagination helpers for consistent API responses
 */

const { PAGINATION } = require('../../config/constants');

/**
 * Parse pagination parameters from query string
 * 
 * @param {Object} query - Express request query object
 * @returns {Object} Parsed pagination params { page, limit, skip }
 */
function parsePaginationParams(query) {
  const page = Math.max(
    parseInt(query.page) || PAGINATION.DEFAULT_PAGE,
    PAGINATION.MIN_PAGE
  );
  
  const limit = Math.min(
    Math.max(
      parseInt(query.limit) || PAGINATION.DEFAULT_LIMIT,
      PAGINATION.MIN_LIMIT
    ),
    PAGINATION.MAX_LIMIT
  );
  
  const skip = (page - 1) * limit;
  
  return { page, limit, skip };
}

/**
 * Build pagination metadata for response
 * 
 * @param {number} page - Current page number
 * @param {number} limit - Items per page
 * @param {number} total - Total number of items
 * @returns {Object} Pagination metadata
 */
function buildPaginationResponse(page, limit, total) {
  const totalPages = Math.ceil(total / limit);
  
  return {
    page,
    limit,
    total,
    totalPages,
    hasNext: page < totalPages,
    hasPrev: page > 1,
  };
}

/**
 * Get Prisma pagination query object
 * 
 * @param {number} page - Page number
 * @param {number} limit - Items per page
 * @returns {Object} Prisma query object { skip, take }
 */
function getPrismaPaginationQuery(page, limit) {
  return {
    skip: (page - 1) * limit,
    take: limit,
  };
}

module.exports = {
  parsePaginationParams,
  buildPaginationResponse,
  getPrismaPaginationQuery,
};