// Generated by Phase 1 setup\n


/**
 * CONFIGURATION INDEX
 * 
 * Central export point for all configuration modules
 */

const constants = require('./constants');
const timeouts = require('./timeouts');
const rateLimits = require('./rate-limits');

module.exports = {
  ...constants,
  ...timeouts,
  ...rateLimits,
};