// Generated by Phase 1 setup\n


/**
 * RATE LIMITING CONFIGURATIONS
 * 
 * Protects API from abuse and ensures fair resource allocation
 */

// ==================== RATE LIMIT TIERS ====================

/**
 * TIER 1: General API Rate Limit (Moderate)
 * Applies to most API endpoints
 */
const API_RATE_LIMIT = {
  windowMs: 15 * 60 * 1000,  // 15 minutes
  max: 100,                   // 100 requests per window
  message: {
    error: 'RATE_LIMIT_EXCEEDED',
    message: 'Too many requests from this IP, please try again later.',
    retryAfter: '15 minutes'
  },
  standardHeaders: true,
  legacyHeaders: false,
};

/**
 * TIER 2: Authentication Rate Limit (Strict)
 * Protects login/register endpoints from brute force
 */
const AUTH_RATE_LIMIT = {
  windowMs: 15 * 60 * 1000,  // 15 minutes
  max: 5,                     // 5 attempts per window
  skipSuccessfulRequests: true,  // Only count failed attempts
  message: {
    error: 'AUTH_RATE_LIMIT_EXCEEDED',
    message: 'Too many login attempts from this IP. Please try again after 15 minutes.',
    retryAfter: '15 minutes'
  },
  standardHeaders: true,
  legacyHeaders: false,
};

/**
 * TIER 3: Payment/Checkout Rate Limit (Restricted)
 * Prevents payment fraud and checkout abuse
 */
const CHECKOUT_RATE_LIMIT = {
  windowMs: 60 * 60 * 1000,  // 1 hour
  max: 10,                    // 10 checkouts per hour
  message: {
    error: 'CHECKOUT_RATE_LIMIT_EXCEEDED',
    message: 'Too many checkout attempts. Please try again after 1 hour.',
    retryAfter: '1 hour'
  },
  standardHeaders: true,
  legacyHeaders: false,
};

module.exports = {
  API_RATE_LIMIT,
  AUTH_RATE_LIMIT,
  CHECKOUT_RATE_LIMIT,
};