// Generated by Phase 1 setup\n


/**
 * TIMEOUT CONFIGURATIONS
 * 
 * Centralized timeout values for orders, prescriptions, and jobs
 */

// ==================== ORDER TIMEOUTS (in hours) ====================
const ORDER_TIMEOUTS = {
  PRESCRIPTION_VERIFICATION: 48,  // 48 hours for prescription verification
  PAYMENT_PENDING: 24,            // 24 hours to complete payment
  STOCK_RESERVATION: 0.5,         // 30 minutes for abandoned checkouts
};

// ==================== PRESCRIPTION EXPIRY (in days) ====================
const PRESCRIPTION_EXPIRY = {
  STANDARD: 30,      // Standard prescriptions expire in 30 days
  CHRONIC: 90,       // Chronic condition prescriptions expire in 90 days
  WARNING_DAYS: 7,   // Send warning 7 days before expiry
};

// ==================== JOB SCHEDULES (cron expressions) ====================
const JOB_SCHEDULES = {
  ORDER_CLEANUP: '0 0 * * *',              // Daily at midnight
  PRESCRIPTION_EXPIRY: '0 1 * * *',        // Daily at 1 AM
  PRESCRIPTION_WARNING: '0 9 * * *',       // Daily at 9 AM
  STOCK_RESTORATION: '*/15 * * * *',       // Every 15 minutes
  RECONCILIATION: '0 3 * * *',             // Daily at 3 AM
  WEBHOOK_CLEANUP: '0 2 * * *',            // Daily at 2 AM
  REFUND_CHECK_PENDING: '*/30 * * * *',    // Every 30 minutes
  REFUND_CHECK_PROCESSING: '0 */2 * * *',  // Every 2 hours
  DATABASE_BACKUP_DAILY: '0 2 * * *',      // Daily at 2 AM
  DATABASE_BACKUP_WEEKLY: '0 3 * * 0',     // Sunday at 3 AM
  DATABASE_BACKUP_MONTHLY: '0 4 1 * *',    // 1st of month at 4 AM
};

// ==================== RETRY CONFIGURATION ====================
const RETRY_CONFIG = {
  MAX_RETRIES: 3,
  RETRY_DELAY_MS: 5000,  // 5 seconds
  BACKOFF_MULTIPLIER: 2,  // Exponential backoff
};

// ==================== WEBHOOK RETENTION ====================
const WEBHOOK_RETENTION = {
  DAYS: 30,  // Keep processed webhooks for 30 days
};

// ==================== NOTIFICATION THRESHOLDS ====================
const NOTIFICATION_THRESHOLDS = {
  CONSECUTIVE_FAILURES: 3,  // Alert after 3 consecutive failures
};

module.exports = {
  ORDER_TIMEOUTS,
  PRESCRIPTION_EXPIRY,
  JOB_SCHEDULES,
  RETRY_CONFIG,
  WEBHOOK_RETENTION,
  NOTIFICATION_THRESHOLDS,
};